docs: Update part about DCOR
DC-analysis/dclab pull request #208
Opened 2023-02-05 17:50 UTC by B-Hartmann

Update the docs about DCOR: How to manage API Tokens and how to access data on a different DCOR instance.

Closes #182

2023-02-05 21:58 UTC, paulmueller commented on docs/sec_av_dcor.rst
> +.. figure:: figures/API_Token_website.PNG
please use lower-case suffixes (.png)

2023-02-05 22:01 UTC, paulmueller commented
Thanks for updating the docs. I just had a minor comment. Let me know whether you would like to change anything, else I will merge :pray:

2023-02-06 05:38 UTC, B-Hartmann commented on docs/sec_av_dcor.rst
> +.. figure:: figures/API_Token_website.PNG
Changed it.

2023-02-06 05:45 UTC, B-Hartmann commented
I updated the image with the part about API tokens from the DCOR website to show some more details. This is ready to be merged!

2023-02-06 07:07 UTC, paulmueller requested changes
Please also rename the PNG file. Otherwise building the docs will fail on non-Windows system, since POSIX paths are case-sensitive.

2023-02-06 09:38 UTC, paulmueller approved these changes

2023-02-06 09:39 UTC, merged